blank_issues_enabled: false
contact_links:
  - name: Mobile Legends: Go Go Community
    url: https://github.com/bybyKD/magic-chess-gogo-auction/discussions
    about: For gameplay questions or general discussion
